[project]
name = "mcp-resource"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "httpx",
    "mcp[cli]>=1.9.4",
    "pymupdf>=1.26.1",
]

[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"
